services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend
          action: sync
          target: /app
          ignore:
            - node_modules/
            - dist/
