"""seed admin user

Revision ID: 8c68fbf858fc
Revises: 19bb625a7497
Create Date: 2026-02-05 12:51:57.713156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from passlib.context import CryptContext

# revision identifiers, used by Alembic.
revision: str = '8c68fbf858fc'
down_revision: Union[str, Sequence[str], None] = '19bb625a7497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    hp = pwd_context.hash("password123")  # compute hash here (optional)
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            INSERT INTO users (email, username, hashed_password, full_name, is_active)
            VALUES (:email, :username, :hp, :full_name, :active)
            """
        ),
        {"email": "admin@test.com", "username": "admin", "hp": hp, "full_name": "Administrator", "active": True},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM users WHERE email = :email"), {"email": "admin@test.com"})
    # ### end Alembic commands ###
